[package]

name = "allegro_primitives"
version = "0.0.0"
authors = [ "SiegeLord <slabode@aim.com>" ]

[lib]

name = "allegro_primitives"
path = "src/lib.rs"

[dependencies.allegro]

path = "../allegro"
