[package]

name = "allegro"
version = "0.0.0"
license = "Zlib"
repository = "https://github.com/SiegeLord/RustAllegro"
documentation = "http://siegelord.github.io/RustAllegro/doc/allegro/index.html"
keywords = ["input", "windowing", "opengl", "direct3d"]
authors = [ "SiegeLord <slabode@aim.com>" ]
description = "Allegro 5 core library Rust wrapper"

[lib]

name = "allegro"
path = "src/lib.rs"
