[package]

name = "allegro_acodec"
version = "0.0.0"
authors = [ "SiegeLord <slabode@aim.com>" ]

[[lib]]

name = "allegro_acodec"
path = "src/lib.rs"

[dependencies.allegro]

path = "../allegro"

[dependencies.allegro_audio]

path = "../allegro_audio"
